# Generated by Django 5.2.11 on 2026-03-18 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_importhistory'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='transaction',
            name='core_transa_user_id_5b29f4_idx',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='status',
        ),
    ]
