# Generated by Django 5.2.11 on 2026-03-18 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='normalized_vendor',
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
    ]
