# Generated by Django 5.2.11 on 2026-03-27 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_subscription',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
